In [0]:
from __future__ import print_function
import torch

In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[2.7585e-37, 0.0000e+00, 1.6675e-43],
        [5.6052e-44, 1.6816e-43, 6.1657e-44],
        [4.4842e-44, 1.6956e-43, 6.1657e-44],
        [4.4842e-44, 1.7096e-43, 5.7453e-44],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


In [5]:
x = torch.rand(5,3)
print(x)

tensor([[0.6404, 0.1784, 0.0682],
        [0.7415, 0.8107, 0.8368],
        [0.6444, 0.3370, 0.5968],
        [0.5204, 0.4992, 0.5261],
        [0.0454, 0.8758, 0.0689]])


In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [11]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 1.8035, -0.8945,  1.7896],
        [-0.6373,  0.1600, -0.6576],
        [-0.9412, -1.8026,  0.2825],
        [ 0.0046,  1.2979,  0.0292],
        [-1.0843,  1.6287, -0.9082]])


In [12]:
print(x.size())

torch.Size([5, 3])


In [14]:
y = torch.rand(5,3)
print(x + y)

tensor([[ 2.3331, -0.5990,  1.8055],
        [ 0.0759,  0.9929, -0.6393],
        [ 0.0032, -1.5841,  1.0670],
        [ 0.3306,  2.2262,  0.5509],
        [-0.1473,  2.1412,  0.0567]])


In [15]:
print(torch.add(x, y))

tensor([[ 2.3331, -0.5990,  1.8055],
        [ 0.0759,  0.9929, -0.6393],
        [ 0.0032, -1.5841,  1.0670],
        [ 0.3306,  2.2262,  0.5509],
        [-0.1473,  2.1412,  0.0567]])


In [16]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 2.3331, -0.5990,  1.8055],
        [ 0.0759,  0.9929, -0.6393],
        [ 0.0032, -1.5841,  1.0670],
        [ 0.3306,  2.2262,  0.5509],
        [-0.1473,  2.1412,  0.0567]])


In [17]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
x = torch.randn(1)
print(x) 
print(x.item())

tensor([0.1180])
0.11797789484262466


In [25]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [26]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [27]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [28]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [0]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  y = torch.ones_like(x, device=device)
  x = x.to(device)
  z = x + y
  print(z)
  print(z.to("cpu", torch.double))

In [0]:
# autograd tutorial 

In [32]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [33]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [34]:
print(y.grad_fn)

In [35]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [36]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [37]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [39]:
x = torch.randn(3, requires_grad=True)

y = x * 2
print(y)
while y.data.norm() < 1000:
  y = y * 2
print(y)

tensor([ 0.4240,  1.6771, -0.5042], grad_fn=<MulBackward0>)
tensor([ 434.2087, 1717.3851, -516.3360], grad_fn=<MulBackward0>)


In [40]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [42]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.conv1 = nn.Conv2d(1, 6, 3)
    self.conv2 = nn.Conv2d(6, 16, 3)
    self.fc1 = nn.Linear(16 * 6 * 6, 120)
    self.fc2 = nn.Linear(120, 84)
    self.fc3 = nn.Linear(84, 10)

  def forward(self, x):
    x = F.max_pool2d(F.relu(self.conv1(x)), (2,2))
    x = F.max_pool2d(F.relu(self.conv2(x)), 2)
    x = x.view(-1, self.num_flat_features(x))
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    return x

  def num_flat_features(self, x):
    size = x.size()[1:]
    num_features = 1
    for s in size:
      num_features *= s
    return num_features

net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [43]:
params = list(net.parameters())
print(len(params))
print(params[0].size())

10
torch.Size([6, 1, 3, 3])


In [44]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[-0.0920, -0.0159, -0.0633,  0.0683,  0.0040, -0.0760, -0.1888, -0.0222,
         -0.0757,  0.0020]], grad_fn=<AddmmBackward>)


In [0]:
net.zero_grad()
out.backward(torch.randn(1,10))

In [48]:
output = net(input)
target = torch.randn(10)
target = target.view(1, -1)
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(0.6959, grad_fn=<MseLossBackward>)


In [49]:
print(loss.grad_fn)
print(loss.grad_fn.next_functions[0][0])
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])

In [0]:
net.zero_grad()
loss.backward()

In [0]:
import torch.optim as optim

optimizer = optim.SGD(net.parameters(), lr=0.01)

optimizer.zero_grad()
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()